// Auto-generated by scripts/generate-registry.mjs. Do not edit directly.
import type {
  SolatGuide,
  SourceItem,
  PrayerCategory,
  Hukum,
  ReviewStatus,
} from "@/lib/content-schema";

export type {
  SolatGuide,
  SourceItem,
  PrayerCategory,
  Hukum,
  ReviewStatus,
};

// Re-export Guide as alias for SolatGuide for backward compatibility
export type Guide = SolatGuide;

export const sources: readonly SourceItem[] = [
  {
    "id": "jakim-panduan-solat-sunat",
    "title": "Panduan Sembahyang Sunat",
    "author": "Jabatan Kemajuan Islam Malaysia (JAKIM)",
    "publisher": "Jabatan Kemajuan Islam Malaysia (JAKIM)",
    "year": 2018,
    "type": "government_religious_authority",
    "url": "https://www.islam.gov.my",
    "licenseOrPermission": "Penerbitan Rasmi Agensi Agama Kerajaan Malaysia untuk bimbingan ibadah awam.",
    "notes": "Rujukan panduan ibadah solat sunat rasmi di Malaysia mengikut Mazhab Syafi'i."
  },
  {
    "id": "jakim-panduan-tarawih",
    "title": "Panduan Sembahyang Sunat Tarawih",
    "author": "Jabatan Kemajuan Islam Malaysia (JAKIM)",
    "publisher": "Jabatan Kemajuan Islam Malaysia (JAKIM)",
    "year": 2020,
    "type": "government_religious_authority",
    "url": "https://www.e-solat.gov.my/portalassets/files/Penerbitan/Panduan-Solat-Tarawih-Jakim---2020.pdf",
    "licenseOrPermission": "Penerbitan Panduan Rasmi JAKIM.",
    "notes": "Panduan tatacara solat tarawih, bacaan surah, dan doa kamilin."
  },
  {
    "id": "muftiwp-irsyad",
    "title": "Koleksi Irsyad Al-Fatwa & Al-Kafi li al-Fatawi (Hukum Solat Sunat)",
    "author": "Pejabat Mufti Wilayah Persekutuan",
    "publisher": "Pejabat Mufti Wilayah Persekutuan",
    "year": 2023,
    "type": "government_religious_authority",
    "url": "https://www.muftiwp.gov.my",
    "licenseOrPermission": "Portal Fatwa Rasmi Kerajaan Wilayah Persekutuan Malaysia.",
    "notes": "Penjelasan hukum, qada solat sunat, dan kaedah pelaksanaan solat sunat Mazhab Syafi'i."
  },
  {
    "id": "al-fiqh-al-manhaji",
    "title": "Al-Fiqh al-Manhaji 'ala Madhhab al-Imam al-Shafi'i",
    "author": "Dr. Mustafa al-Khin, Dr. Mustafa al-Bugha, 'Ali al-Syarbaji",
    "publisher": "Dar al-Qalam (Terjemahan Jabatan Kemajuan Islam Malaysia)",
    "year": 2009,
    "type": "classical_shafii_text",
    "url": "https://www.e-solat.gov.my",
    "licenseOrPermission": "Teks fiqh muktabar Mazhab Syafi'i yang diiktiraf di institusi pengajian Islam Malaysia.",
    "notes": "Hukum, bilangan rakaat, tatacara dan rukun solat sunat mengikut pandangan muktamad Mazhab Syafi'i."
  },
  {
    "id": "al-azkar-nawawi",
    "title": "Kitab al-Adhkar al-Muntakhabah min Kalam Sayyid al-Abrar",
    "author": "Imam Yahya bin Sharaf al-Nawawi",
    "publisher": "Dar al-Fikr",
    "year": 1994,
    "type": "classical_shafii_text",
    "url": "https://sunnah.com",
    "licenseOrPermission": "Kitab rujukan klasik doa dan zikir harian.",
    "notes": "Doa witir, istikharah, zikir selepas solat, dan doa-doa masyhur."
  },
  {
    "id": "sahih-bukhari",
    "title": "Al-Jami' al-Sahih (Sahih al-Bukhari)",
    "author": "Imam Muhammad bin Isma'il al-Bukhari",
    "publisher": "Dar Tawq an-Najah",
    "year": 2001,
    "type": "hadith_compilation",
    "url": "https://sunnah.com/bukhari",
    "licenseOrPermission": "Kitab Hadith Sahih primer domain awam.",
    "notes": "Hadith dalil solat Tahajjud, Dhuha, Kusuf, Istikharah, dan Wuduk."
  },
  {
    "id": "sahih-muslim",
    "title": "Al-Musnad al-Sahih (Sahih Muslim)",
    "author": "Imam Muslim bin al-Hajjaj an-Naysaburi",
    "publisher": "Dar Ihya' al-Turath al-'Arabi",
    "year": 1955,
    "type": "hadith_compilation",
    "url": "https://sunnah.com/muslim",
    "licenseOrPermission": "Kitab Hadith Sahih primer domain awam.",
    "notes": "Hadith dalil solat Rawatib, Awwabin, Musafir, dan Istisqa'."
  },
  {
    "id": "sunan-tirmidhi",
    "title": "Al-Jami' al-Mukhtasar (Jami' at-Tirmidhi)",
    "author": "Imam Abu 'Isa Muhammad bin 'Isa at-Tirmidhi",
    "publisher": "Dar al-Gharb al-Islami",
    "year": 1998,
    "type": "hadith_compilation",
    "url": "https://sunnah.com/tirmidhi",
    "licenseOrPermission": "Kitab Hadith Sunan domain awam.",
    "notes": "Hadith fadhilat solat Tasbih (No. 481), Isyraq (No. 586), dan solat Hajat."
  },
  {
    "id": "sunan-abi-dawud",
    "title": "Sunan Abi Dawud",
    "author": "Imam Abu Dawud Sulaiman bin al-Ash'ath",
    "publisher": "Dar ar-Risalah al-'Alamiyyah",
    "year": 2009,
    "type": "hadith_compilation",
    "url": "https://sunnah.com/abudawud",
    "licenseOrPermission": "Kitab Hadith Sunan domain awam.",
    "notes": "Hadith tatacara solat Tasbih, Witir, Taubat, dan Istisqa'."
  },
  {
    "id": "riyadus-salihin",
    "title": "Riyad al-Salihin min Kalam Sayyid al-Mursalin",
    "author": "Imam Yahya bin Sharaf al-Nawawi",
    "publisher": "Dar Ibn Kathir",
    "year": 2007,
    "type": "classical_shafii_text",
    "url": "https://sunnah.com/riyadussalihin",
    "licenseOrPermission": "Kitab rujukan himpunan hadith amalan harian.",
    "notes": "Bab fadhilat solat-solat sunat dan adab beribadah."
  }
] as const;

export const guides: readonly SolatGuide[] = [
  {
    "id": "solat-aidiladha",
    "slug": "aidiladha",
    "title": "Solat Sunat Aidiladha",
    "titleArabic": "صَلَاةُ عِيدِ الْأَضْحَى",
    "category": "raya_fenomena",
    "shortPurpose": "Menzahirkan pengagungan syiar Islam, kesyukuran, dan pembuka ibadah korban sempena Hari Raya Korban.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Pagi 10 Zulhijjah, bermula selepas matahari naik setinggi satu penggalah (~20-28 minit selepas syuruk) hingga sebelum masuk waktu Zuhur. Disunatkan disegerakan berbanding Aidilfitri untuk melapangkan masa menyembelih korban.",
      "suggestedTimeOfDay": "dhuha"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةً لِعِيدِ الْأَضْحَى رَكْعَتَيْنِ أَدَاءً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatan li 'idil-adha rak'ataini adaan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidiladha dua rakaat tunai kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Aidiladha"
      },
      {
        "label": "Makmum",
        "arabic": "أُصَلِّي سُنَّةً لِعِيدِ الْأَضْحَى رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatan li 'idil-adha rak'ataini makmuman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidiladha dua rakaat sebagai makmum kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Aidiladha"
      },
      {
        "label": "Imam",
        "arabic": "أُصَلِّي سُنَّةً لِعِيدِ الْأَضْحَى رَكْعَتَيْنِ إِمَامًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatan li 'idil-adha rak'ataini imaman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidiladha dua rakaat sebagai imam kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Aidiladha"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat Aidiladha disertakan ketika takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "7 Takbir Tambahan Rakaat Pertama",
        "description": "Membaca doa iftitah disusuli 7 takbir tambahan diselangi bacaan tasbih.",
        "isRukun": false
      },
      {
        "stepNumber": 3,
        "title": "Al-Fatihah, Surah, Rukuk & Sujud",
        "description": "Membaca Al-Fatihah dan surah, serta menyempurnakan rukuk dan sujud.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "5 Takbir Tambahan Rakaat Kedua",
        "description": "Bangkit dari sujud kedua, bertakbir 5 kali diselangi bacaan tasbih.",
        "isRukun": false
      },
      {
        "stepNumber": 5,
        "title": "Al-Fatihah, Tahiyat Akhir & Salam",
        "description": "Membaca Al-Fatihah, surah lazim, tahiyat akhir dan salam.",
        "isRukun": true
      },
      {
        "stepNumber": 6,
        "title": "Khutbah Aidiladha",
        "description": "Mendengar khutbah hari raya berkaitan hikmah korban dan ketakwaan Nabi Ibrahim a.s.",
        "isRukun": false
      }
    ],
    "recommendedPractice": [
      {
        "title": "Sunat Sebelum Solat Aidiladha",
        "description": "Disunatkan tidak menjamah makanan sebelum solat sehingga pulang dan menikmati daging korban (berbeza dengan Aidilfitri yang disunatkan makan sedikit tamar sebelum solat).",
        "recommendedSurahs": [
          "Al-A'la",
          "Al-Ghasyiyah"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat Aidiladha lazimnya dimulakan sekitar jam 8.00 - 8.30 pagi, lebih awal daripada Aidilfitri, agar proses penyembelihan dan pengagihan lembu/kambing korban dapat disegerakan.",
    "variationsNotes": "Takbir Muqayyad (takbir mengiringi setiap solat fardu) disyariatkan bermula Subuh hari Arafah (9 Zulhijjah) sehingga waktu Asar hari Tasyriq ke-3 (13 Zulhijjah).",
    "doa": [
      {
        "title": "Doa Selepas Solat Sunat Aidiladha",
        "arabic": "اللَّهُمَّ تَقَبَّلْ مِنَّا صَلَاتَنَا وَدُعَاءَنَا وَقُرْبَانَنَا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ.",
        "rumi": "Allahumma taqabbal minna salatana wa du'a'ana wa qurbanana innaka antas-sami'ul-'alim, wa tub 'alaina innaka antat-tawwabur-rahim.",
        "translation": "Ya Allah, terimalah daripada kami solat kami, doa kami, dan ibadah korban kami. Sesungguhnya Engkau Maha Mendengar lagi Maha Mengetahui. Berilah keampunan kepada kami, sesungguhnya Engkau Maha Penerima Taubat lagi Maha Penyayang.",
        "dir": "rtl",
        "sourceRef": "al-azkar-nawawi",
        "sourcePage": "Doa Ibadah Korban"
      }
    ],
    "interactiveTool": {
      "toolType": "takbir-tracker",
      "rakaat1Takbir": 7,
      "rakaat2Takbir": 5,
      "intermediateTasbih": "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ"
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-aidilfitri",
    "slug": "aidilfitri",
    "title": "Solat Sunat Aidilfitri",
    "titleArabic": "صَلَاةُ عِيدِ الْفِطْرِ",
    "category": "raya_fenomena",
    "shortPurpose": "Menzahirkan syiar kegembiraan dan kesyukuran atas kemenangan menyempurnakan ibadah Ramadan.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Pagi 1 Syawal, bermula selepas matahari terbit dan naik setinggi satu penggalah (~28 minit selepas syuruk) hingga sebelum gelincir matahari (masuk waktu Zuhur).",
      "suggestedTimeOfDay": "dhuha"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ عِيدِ الْفِطْرِ رَكْعَتَيْنِ أَدَاءً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnata 'idil-fitri rak'ataini adaan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidilfitri dua rakaat tunai kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Hari Raya"
      },
      {
        "label": "Makmum",
        "arabic": "أُصَلِّي سُنَّةَ عِيدِ الْفِطْرِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnata 'idil-fitri rak'ataini makmuman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidilfitri dua rakaat sebagai makmum kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Hari Raya"
      },
      {
        "label": "Imam",
        "arabic": "أُصَلِّي سُنَّةَ عِيدِ الْفِطْرِ رَكْعَتَيْنِ إِمَامًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnata 'idil-fitri rak'ataini imaman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Aidilfitri dua rakaat sebagai imam kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Hari Raya"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Mengangkat takbiratul ihram dengan menghadirkan niat solat sunat Aidilfitri dalam hati.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Doa Iftitah & 7 Takbir Tambahan",
        "description": "Membaca doa iftitah disusuli 7 kali takbir tambahan pada rakaat pertama. Setiap sela takbir disunatkan membaca tasbih.",
        "isRukun": false
      },
      {
        "stepNumber": 3,
        "title": "Surah Al-Fatihah & Surah Pilihan",
        "description": "Membaca Al-Fatihah (rukun), kemudian disunatkan membaca Surah Qaf atau Surah Al-A'la.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Rukuk, I'tidal & Dua Sujud Rakaat Pertama",
        "description": "Menyempurnakan rukun fi'li dengan tumakninah.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Bangkit ke Rakaat Kedua & 5 Takbir Tambahan",
        "description": "Bangkit dengan takbir intiqalat, kemudian bertakbir 5 kali diselangi tasbih.",
        "isRukun": false
      },
      {
        "stepNumber": 6,
        "title": "Al-Fatihah, Rukuk, Sujud, Tahiyat Akhir & Salam",
        "description": "Membaca Al-Fatihah, surah lazim, menyempurnakan rukun hingga salam.",
        "isRukun": true
      },
      {
        "stepNumber": 7,
        "title": "Mendengar Khutbah Hari Raya",
        "description": "Sunat mendengar dua khutbah Hari Raya sekiranya solat dilakukan secara berjemaah.",
        "isRukun": false
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Solat Hari Raya",
        "description": "Rakaat pertama: Surah Al-A'la (atau Surah Qaf). Rakaat kedua: Surah Al-Ghasyiyah (atau Surah Al-Qamar).",
        "recommendedSurahs": [
          "Al-A'la",
          "Al-Ghasyiyah",
          "Qaf",
          "Al-Qamar"
        ]
      }
    ],
    "commonLocalPractice": "Masyarakat Islam Malaysia mengumandangkan takbir raya sejak malam 1 Syawal hingga sebelum solat dimulakan. Selepas solat, jemaah mendengar khutbah Aidilfitri dan bersalaman memohon kemaafan.",
    "variationsNotes": "Takbir tambahan 7 kali dan 5 kali hukumnya sunat hay'ah. Jika imam terlupa dan terus membaca al-Fatihah, tidak perlu sujud sahwi dan tidak perlu mengulang takbir tersebut.",
    "doa": [
      {
        "title": "Doa Selepas Solat Sunat Aidilfitri",
        "arabic": "اللَّهُمَّ تَقَبَّلْ مِنَّا صَلَاتَنَا وَدُعَاءَنَا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ. اللَّهُمَّ اجْعَلْ دِينَنَا دِينَ النَّبِيِّ مُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، وَإِيمَانَنَا إِيمَانَ الْمُؤْمِنِينَ.",
        "rumi": "Allahumma taqabbal minna salatana wa du'a'ana innaka antas-sami'ul-'alim, wa tub 'alaina innaka antat-tawwabur-rahim. Allahummaj'al dinana dinan-nabiyyi Muhammadin sallallahu 'alaihi wa sallam, wa imanana imanal-mu'minin.",
        "translation": "Ya Allah, terimalah solat kami dan doa kami, sesungguhnya Engkau Maha Mendengar lagi Maha Mengetahui. Terimalah taubat kami, sesungguhnya Engkau Maha Penerima Taubat lagi Maha Penyayang. Ya Allah, jadikanlah agama kami mengikut agama Nabi Muhammad SAW, dan keimanan kami seperti keimanan orang-orang yang beriman.",
        "dir": "rtl",
        "sourceRef": "al-azkar-nawawi",
        "sourcePage": "Doa Hari Raya"
      }
    ],
    "interactiveTool": {
      "toolType": "takbir-tracker",
      "rakaat1Takbir": 7,
      "rakaat2Takbir": 5,
      "intermediateTasbih": "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ"
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-awwabin",
    "slug": "awwabin",
    "title": "Solat Sunat Awwabin",
    "titleArabic": "صَلَاةُ الْأَوَّابِينَ",
    "category": "harian",
    "shortPurpose": "Solat orang-orang yang sentiasa bertaubat, dilakukan antara waktu Maghrib dan Isyak bagi memelihara iman.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2,
      4,
      6
    ],
    "timeGuidance": {
      "description": "Dilakukan antara waktu selepas solat Maghrib (selepas Ba'diyyah Maghrib) sehingga masuk waktu Isyak.",
      "suggestedTimeOfDay": "maghrib"
    },
    "niat": [
      {
        "label": "Set 1: Memelihara Iman (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الْأَوَّابِينَ مَعَ حِفْظِ الْإِيمَانِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-awwabina ma'a hifzil-imani rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Awwabin berserta memelihara iman dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Sunat Awwabin"
      },
      {
        "label": "Set 2: Bertaubat (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الْأَوَّابِينَ مَعَ التَّوْبَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-awwabina ma'at-taubati rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Awwabin berserta taubat dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Sunat Awwabin"
      },
      {
        "label": "Set 3: Istikharah (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الْأَوَّابِينَ مَعَ الِاسْتِخَارَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-awwabina ma'al-istikharati rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Awwabin berserta istikharah dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Sunat Awwabin"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Solat Ba'diyyah Maghrib Terlebih Dahulu",
        "description": "Menyempurnakan solat fardu Maghrib dan solat sunat Ba'diyyah Maghrib 2 rakaat.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat Solat Awwabin (Setiap 2 Rakaat 1 Salam)",
        "description": "Mendirikan solat 2 rakaat demi 2 rakaat sehingga 6 rakaat mengikut niat masing-masing.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rukun Pergerakan",
        "description": "Membaca Al-Fatihah, surah lazim, rukuk, iktidal, dua sujud, tahiyat akhir dan salam.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Awwabin",
        "description": "Rakaat 1: Surah Al-Kafirun. Rakaat 2: Surah Al-Ikhlas (atau membaca surah Al-Falaq dan An-Nas pada set berikutnya).",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas",
          "Al-Falaq",
          "An-Nas"
        ]
      }
    ],
    "commonLocalPractice": "Amalan solat Awwabin dihidupkan di madrasah, pondok, dan surau di Malaysia ketika waktu menunggu masuknya waktu solat Isyak.",
    "variationsNotes": "Diriwayatkan hadith bahawa sesiapa yang solat 6 rakaat selepas Maghrib tanpa diselangi perkataan buruk, diberi pahala seperti beribadah 12 tahun (Jami' at-Tirmidhi No. 435).",
    "doa": [
      {
        "title": "Doa Memohon Penetapan Iman Selepas Awwabin",
        "arabic": "اللَّهُمَّ سَدِّدْنِي بِالْإِيمَانِ، وَاحْفَظْهُ عَلَيَّ فِي حَيَاتِي، وَعِنْدَ وَفَاتِي، وَبَعْدَ مَمَاتِي.",
        "rumi": "Allahumma saddidni bil-iman, wahfazhu 'alayya fi hayati, wa 'inda wafati, wa ba'da mamati.",
        "translation": "Ya Allah, tetapkanlah diriku dengan iman, dan peliharalah iman itu ke atasku sepanjang hayatku, tatkala saat kewafatanku, dan selepas kematianku.",
        "dir": "rtl",
        "sourceRef": "al-azkar-nawawi",
        "sourcePage": "Doa Menjaga Iman"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-dhuha",
    "slug": "dhuha",
    "title": "Solat Sunat Dhuha",
    "titleArabic": "صَلَاةُ الضُّحَى",
    "category": "harian",
    "shortPurpose": "Menzahirkan kesyukuran atas nikmat persendian tubuh badan serta memohon keluasan rezeki yang berkat.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2,
      4,
      8,
      12
    ],
    "timeGuidance": {
      "description": "Bermula kira-kira 28 minit selepas syuruk hingga sebelum matahari tergelincir (sebelum masuk waktu Zuhur). Waktu paling afdal adalah ketika panas matahari mula terasa (sekitar jam 9.30 - 11.00 pagi).",
      "suggestedTimeOfDay": "dhuha"
    },
    "niat": [
      {
        "label": "2 Rakaat",
        "arabic": "أُصَلِّي سُنَّةَ الضُّحَى رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatad-duha rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Dhuha dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Dhuha"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat Dhuha dalam hati bersama takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rakaat Pertama: Al-Fatihah & Surah Asy-Syams",
        "description": "Membaca Al-Fatihah diikuti Surah Asy-Syams (atau Surah Al-Kafirun).",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rukuk, I'tidal & Dua Sujud",
        "description": "Menyempurnakan rukun fi'li dengan tumakninah.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Rakaat Kedua: Al-Fatihah & Surah Ad-Dhuha",
        "description": "Membaca Al-Fatihah diikuti Surah Ad-Dhuha (atau Surah Al-Ikhlas).",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Tahiyat Akhir & Salam",
        "description": "Duduk membaca tasyahhud dan selawat, kemudian memberi salam.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Solat Dhuha",
        "description": "Rakaat 1: Surah Asy-Syams (atau Al-Kafirun). Rakaat 2: Surah Ad-Dhuha (atau Al-Ikhlas).",
        "recommendedSurahs": [
          "Asy-Syams",
          "Ad-Dhuha",
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di pejabat, sekolah, dan institusi di Malaysia, ramai umat Islam melazimi solat Dhuha pada waktu rehat pagi sebagai amalan pembuka rezeki harian.",
    "variationsNotes": "Sekurang-kurangnya 2 rakaat, afdal 8 rakaat, dan paling banyak 12 rakaat, dilakukan 2 rakaat bagi setiap 1 salam.",
    "doa": [
      {
        "title": "Doa Solat Dhuha Masyhur",
        "arabic": "اللَّهُمَّ إِنَّ الضُّحَاءَ ضُحَاؤُكَ، وَالْبَهَاءَ بَهَاؤُكَ، وَالْجَمَالَ جَمَالُكَ، وَالْقُوَّةَ قُوَّتُكَ، وَالْقُدْرَةَ قُدْرَتُكَ، وَالْعِصْمَةَ عِصْمَتُكَ. اللَّهُمَّ إِنْ كَانَ رِزْقِي فِي السَّمَاءِ فَأَنْزِلْهُ، وَإِنْ كَانَ فِي الْأَرْضِ فَأَخْرِجْهُ، وَإِنْ كَانَ مُعَسَّرًا فَيَسِّرْهُ، وَإِنْ كَانَ حَرَامًا فَطَهِّرْهُ، وَإِنْ كَانَ بَعِيدًا فَقَرِّبْهُ، بِحَقِّ ضُحَائِكَ وَبَهَائِكَ وَجَمَالِكَ وَقُوَّتِكَ وَقُدْرَتِكَ، آتِنِي مَا آتَيْتَ عِبَادَكَ الصَّالِحِينَ.",
        "rumi": "Allahumma innad-duha'a duha'uka, wal-baha'a baha'uka, wal-jamala jamaluka, wal-quwwata quwwatuka, wal-qudrata qudratuka, wal-'ismata 'ismatuka. Allahumma in kana rizqi fis-sama'i fa-anzilhu, wa in kana fil-ardi fa-akhrijhu, wa in kana mu'assaran fa-yassirhu, wa in kana haraman fa-tahhirhu, wa in kana ba'idan fa-qarribhu, bihaqqi duha'ika wa baha'ika wa jamalika wa quwwatika wa qudratika, atini ma ataita 'ibadakas-salihin.",
        "translation": "Ya Allah, sesungguhnya waktu Dhuha itu waktu Dhuha-Mu, kecantikan itu kecantikan-Mu, keindahan itu keindahan-Mu, kekuatan itu kekuatan-Mu, kekuasaan itu kekuasaan-Mu, dan perlindungan itu perlindungan-Mu. Ya Allah, jika rezekiku berada di langit maka turunkanlah ia, jika di bumi maka keluarkanlah ia, jika sukar maka permudahkanlah ia, jika haram maka sucikanlah ia, dan jika jauh maka dekatkanlah ia. Berkat kebenaran Dhuha-Mu, keagungan-Mu, keindahan-Mu, kekuatan-Mu, dan kekuasaan-Mu, kurniakanlah kepadaku apa yang telah Engkau kurniakan kepada hamba-hamba-Mu yang soleh.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Doa Solat Dhuha"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-gerhana-matahari",
    "slug": "gerhana-matahari",
    "title": "Solat Sunat Gerhana Matahari (Kusuf)",
    "titleArabic": "صَلَاةُ كُسُوفِ الشَّمْسِ",
    "category": "raya_fenomena",
    "shortPurpose": "Solat khas 2 rakaat dengan 2 qiyam dan 2 rukuk setiap rakaat ketika berlakunya fenomena gerhana matahari.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Bermula apabila fenomena gerhana matahari mula kelihatan sehingga matahari terang semula.",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الْكُسُوفِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-kusufi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat gerhana matahari dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Gerhana"
      },
      {
        "label": "Makmum",
        "arabic": "أُصَلِّي سُنَّةَ الْكُسُوفِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-kusufi rak'ataini makmuman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat gerhana matahari dua rakaat sebagai makmum kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Gerhana"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Qiyam Pertama Rakaat 1",
        "description": "Takbiratul ihram bersama niat, membaca doa iftitah, Al-Fatihah dan surah panjang (contohnya Surah Al-Baqarah).",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rukuk Pertama Rakaat 1",
        "description": "Rukuk yang panjang dengan bertasbih.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "I'tidal & Qiyam Kedua Rakaat 1",
        "description": "Bangkit iktidal, kemudian membaca Al-Fatihah dan surah kedua yang lebih pendek dari surah pertama.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Rukuk Kedua & I'tidal Rakaat 1",
        "description": "Rukuk kedua yang panjang (lebih pendek dari rukuk pertama), diikuti iktidal.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Dua Sujud Rakaat 1",
        "description": "Sujud dua kali yang panjang diselangi duduk antara dua sujud.",
        "isRukun": true
      },
      {
        "stepNumber": 6,
        "title": "Rakaat Kedua (2 Qiyam & 2 Rukuk)",
        "description": "Bangkit ke rakaat kedua dan mengulangi susunan 2 qiyam, 2 rukuk, iktidal, dan 2 sujud.",
        "isRukun": true
      },
      {
        "stepNumber": 7,
        "title": "Tahiyat Akhir, Salam & Khutbah",
        "description": "Duduk membaca tasyahhud akhir, memberi salam, disusuli khutbah gerhana oleh khatib.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Berciri Sirr (Perlahan) pada Bacaan",
        "description": "Bagi gerhana matahari (Kusuf), bacaan surah disunatkan secara sirr (perlahan) mengikut Mazhab Syafi'i, berbeza dengan gerhana bulan (Khusuf) yang dibaca jahar (kuat).",
        "recommendedSurahs": [
          "Al-Baqarah",
          "Ali Imran",
          "An-Nisa'",
          "Al-Ma'idah"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat gerhana diselaraskan oleh Jabatan Agama Islam Negeri (JAIN) dengan hebahan rasmi waktu gerhana dari unit falak, diadakan secara berjemaah di masjid negeri dan kariah.",
    "variationsNotes": "Keunikan solat gerhana ialah adanya 2 rukuk dan 2 kali bacaan Fatihah dalam setiap satu rakaat. Tidak sah mengikut imam solat fardu yang berbeza tatacara.",
    "doa": [
      {
        "title": "Peringatan Gerhana (Sahih al-Bukhari)",
        "arabic": "إِنَّ الشَّمْسَ وَالْقَمَرَ آيَتَانِ مِنْ آيَاتِ اللَّهِ لَا يَنْكَسِفَانِ لِمَوْتِ أَحَدٍ وَلَا لِحَيَاتِهِ، فَإِذَا رَأَيْتُمُوهُمَا فَادْعُوا اللَّهَ وَصَلُّوا حَتَّى يَنْجَلِيَ",
        "rumi": "Innasy-syamsa wal-qamara ayatani min ayatillah, la yankasifani li mauti ahadin wa la lihayatih, fa-iza ra'aitumuhuma fad'ullaha wa sallu hatta yanjaliya",
        "translation": "Sesungguhnya matahari dan bulan adalah dua tanda daripada tanda-tanda kebesaran Allah. Keduanya tidak gerhana kerana kematian seseorang mahupun kelahirannya. Maka apabila kamu melihatnya, berdoalah kepada Allah dan solatlah sehingga gerhana itu selesai.",
        "dir": "rtl",
        "sourceRef": "sahih-bukhari",
        "sourcePage": "Kitab al-Kusuf, Hadith No. 1044"
      }
    ],
    "interactiveTool": {
      "toolType": "kusuf-visualizer",
      "rakaatCount": 2,
      "qiyamPerRakaat": 2,
      "rukukPerRakaat": 2,
      "sequenceDescription": "Setiap rakaat mempunyai 2 kali Qiyam (Fatihah + Surah) dan 2 kali Rukuk sebelum turun bersujud dua kali."
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-hajat",
    "slug": "hajat",
    "title": "Solat Sunat Hajat",
    "titleArabic": "صَلَاةُ الْحَاجَةِ",
    "category": "hajat",
    "shortPurpose": "Memohon pertolongan, kemudahan jalan keluar, dan keberkatan daripada Allah SWT bagi sesuatu hajat khusus.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2,
      4,
      12
    ],
    "timeGuidance": {
      "description": "Bila-bila masa sahaja siang atau malam (kecuali pada waktu makruh tahrim). Waktu paling afdal adalah pada waktu sepertiga akhir malam atau selepas solat Isyak.",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الْحَاجَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-hajati rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat hajat dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Hajat"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Menghadirkan hajat dalam hati bersama takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rakaat Pertama",
        "description": "Membaca Surah Al-Fatihah disusuli Ayat al-Kursi (atau surah pilihan).",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rakaat Kedua",
        "description": "Membaca Surah Al-Fatihah disusuli Surah Al-Ikhlas.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Sujud Terakhir",
        "description": "Disunatkan membaca tasbih Nabi Yunus a.s. dalam sujud terakhir dan memohon hajat secara ikhlas.",
        "isRukun": false
      },
      {
        "stepNumber": 5,
        "title": "Tahiyat Akhir & Salam",
        "description": "Duduk membaca tasyahhud akhir, memberi salam, disusuli istighfar, selawat dan doa hajat.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Zikir Selepas Salam Solat Hajat",
        "description": "Membaca Istighfar 10 kali, Selawat ke atas Nabi SAW 10 kali, dan Tasbih 10 kali sebelum menadah tangan berdoa.",
        "recommendedSurahs": [
          "Ayat al-Kursi",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat hajat sering diadakan secara berjemaah di sekolah, masjid, dan kediaman sempena peperiksaan awam (SPM/STPM), memohon kesembuhan pesakit, atau kesejahteraan negara.",
    "variationsNotes": "Solat hajat boleh dilakukan minimum 2 rakaat sehingga 12 rakaat dengan 2 rakaat bagi setiap salam.",
    "doa": [
      {
        "title": "Doa Solat Hajat Masyhur",
        "arabic": "اللَّهُمَّ إِنَّا نَسْأَلُكَ مُوجِبَاتِ رَحْمَتِكَ، وَعَزَائِمَ مَغْفِرَتِكَ، وَالْغَنِيمَةَ مِنْ كُلِّ بِرٍّ، وَالسَّلَامَةَ مِنْ كُلِّ إِثْمٍ، وَالْفَوْزَ بِالْجَنَّةِ، وَالنَّجَاةَ مِنَ النَّارِ. اللَّهُمَّ إِنَّكَ تَسْمَعُ كَلَامِي، وَتَرَى مَكَانِي، وَتَعْلَمُ سِرِّي وَعَلَانِيَتِي، وَلَا يَخْفَى عَلَيْكَ شَيْءٌ مِنْ أَمْرِي، وَأَنَا الْبَائِسُ الْفَقِيرُ، وَالْمُسْتَغِيثُ الْمُسْتَجِيرُ.",
        "rumi": "Allahumma inna nas'aluka mujibati rahmatika, wa 'aza'ima maghfiratika, wal-ghanimata min kulli birr, was-salamata min kulli ithm, wal-fauza bil-jannah, wan-najata minan-nar. Allahumma innaka tasma'u kalami, wa tara makani, wa ta'lamu sirri wa 'alaniyati, wa la yakhfa 'alaika syai'un min amri, wa anal-ba'isul-faqir, wal-mustaghithul-mustajir.",
        "translation": "Ya Allah, sesungguhnya kami memohon kepada-Mu hal-hal yang mewajibkan rahmat-Mu, kepastian keampunan-Mu, keuntungan daripada setiap kebajikan, keselamatan daripada setiap dosa, kejayaan meraih syurga, dan keselamatan daripada api neraka. Ya Allah, sesungguhnya Engkau mendengar perkataanku, melihat tempatku, mengetahui rahsia dan lahiriahku, tiada sesuatu pun daripada urusanku yang tersembunyi daripada-Mu. Daku hamba-Mu yang serba daif lagi fakir, yang memohon pertolongan dan perlindungan.",
        "dir": "rtl",
        "sourceRef": "sunan-tirmidhi",
        "sourcePage": "Kitab al-Solat, Bab Doa al-Hajah"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-istikharah",
    "slug": "istikharah",
    "title": "Solat Sunat Istikharah",
    "titleArabic": "صَلَاةُ الِاسْتِخَارَةِ",
    "category": "hajat",
    "shortPurpose": "Memohon petunjuk, keberkatan, dan ketetapan pilihan terbaik daripada Allah SWT ketika mendepani urusan harus.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Bila-bila masa yang diharuskan solat sunat (bukan pada waktu makruh tahrim). Waktu paling utama adalah pada waktu malam selepas solat Isyak atau sepertiga akhir malam.",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الِاسْتِخَارَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-istikharati rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Istikharah dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Istikharah"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat istikharah dua rakaat ketika takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rakaat Pertama & Kedua",
        "description": "Membaca Al-Fatihah, surah lazim, rukuk, iktidal, sujud dan tahiyat akhir.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Salam & Membaca Doa Istikharah Masyhur",
        "description": "Selesai memberi salam, membaca doa istikharah dan menyebut hajat atau pilihan yang dihadapi.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Istikharah",
        "description": "Rakaat 1: Surah Al-Kafirun. Rakaat 2: Surah Al-Ikhlas.",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, istikharah lazim dilakukan bagi urusan jodoh/perkahwinan, pemilihan tawaran kerjaya, atau menyambung pelajaran ke peringkat lebih tinggi.",
    "variationsNotes": "Jawapan istikharah tidak semestinya datang melalui mimpi; ia boleh dizahirkan dalam bentuk ketenangan hati, kemudahan urusan, atau terhalangnya jalan yang kurang baik.",
    "doa": [
      {
        "title": "Doa Solat Istikharah (Sahih al-Bukhari)",
        "arabic": "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ. اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي ثُمَّ بَارِكْ لِي فِيهِ.",
        "rumi": "Allahumma inni astakhiruka bi'ilmika wa astaqdiruka biqudratika wa as'aluka min fadlikal-'azim, fa-innaka taqdiru wa la aqdiru wa ta'lamu wa la a'lamu wa anta 'allamul-ghuyub. Allahumma in kunta ta'lamu anna hazal-amra khairun li fi dini wa ma'asyi wa 'aqibati amri faqdurhu li wa yassirhu li thumma barik li fih.",
        "translation": "Ya Allah, sesungguhnya aku memohon petunjuk pilihan-Mu dengan ilmu-Mu, memohon kemampuan dengan kekuasaan-Mu, dan memohon kurniaan-Mu yang agung. Sesungguhnya Engkau Maha Berkuasa sedang aku tidak berkuasa, Engkau Maha Mengetahui sedang aku tidak mengetahui, dan Engkaulah Yang Maha Mengetahui segala perkara ghaib. Ya Allah, jika Engkau mengetahui bahawa urusan ini (sebutkan urusan) adalah baik bagiku dalam agamaku, kehidupanku, dan kesudahan urusanku, maka takdirkanlah ia untukku, mudahkanlah ia bagiku, kemudian berkatilah ia untukku.",
        "dir": "rtl",
        "sourceRef": "sahih-bukhari",
        "sourcePage": "Kitab al-Tahajjud, Hadith No. 1162"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-istisqa",
    "slug": "istisqa",
    "title": "Solat Sunat Istisqa'",
    "titleArabic": "صَلَاةُ الِاسْتِسْقَاءِ",
    "category": "raya_fenomena",
    "shortPurpose": "Solat khusus memohon hujan rahmat daripada Allah SWT ketika berlakunya kemarau panjang atau ketiadaan air.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Ditunaikan pada waktu pagi atau siang hari di kawasan lapang (musolla), terutamanya selepas masyarakat berpuasa tiga hari berturut-turut, bertaubat dan bersedekah.",
      "suggestedTimeOfDay": "dhuha"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الِاسْتِسْقَاءِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-istisqa'i rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Istisqa' dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Istisqa'"
      },
      {
        "label": "Makmum",
        "arabic": "أُصَلِّي سُنَّةَ الِاسْتِسْقَاءِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-istisqa'i rak'ataini makmuman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Istisqa' dua rakaat sebagai makmum kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Istisqa'"
      },
      {
        "label": "Imam",
        "arabic": "أُصَلِّي سُنَّةَ الِاسْتِسْقَاءِ رَكْعَتَيْنِ إِمَامًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-istisqa'i rak'ataini imaman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Istisqa' dua rakaat sebagai imam kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Istisqa'"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Persediaan Taubat & Puasa 3 Hari",
        "description": "Pemerintah atau ulama memerintahkan orang ramai bertaubat, bersedekah, mendamaikan sengketa, dan berpuasa 3 hari sebelum keluar pada hari ke-4.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Keluar dengan Pakaian Sederhana & Rendah Diri",
        "description": "Menuju ke kawasan lapang dengan penuh ketundukan (khusyuk dan tawaduk).",
        "isRukun": false
      },
      {
        "stepNumber": 3,
        "title": "Solat 2 Rakaat dengan Takbir Tambahan",
        "description": "Sama seperti Solat Hari Raya: 7 takbir pada rakaat pertama dan 5 takbir pada rakaat kedua.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Khutbah & Membalikkan Selendang (Rida')",
        "description": "Khatib berkhutbah memperbanyakkan istighfar, kemudian membalikkan kain selendang sebagai simbolik mengharapkan perubahan cuaca daripada kemarau kepada hujan.",
        "isRukun": false
      }
    ],
    "recommendedPractice": [
      {
        "title": "Memperbanyakkan Istighfar",
        "description": "Khutbah pertama dimulakan dengan 9 kali istighfar dan khutbah kedua dengan 7 kali istighfar.",
        "recommendedSurahs": [
          "Al-A'la",
          "Al-Ghasyiyah"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat istisqa' dianjurkan oleh Jabatan Mufti atau Majlis Agama Islam Negeri apabila fenomena cuaca panas melampau (El Nino) atau penyusutan paras empangan air berlaku.",
    "variationsNotes": "Khatib dan jemaah disunatkan menadah tangan dengan belakang tapak tangan menghadap ke langit semasa memohon doa hujan sebagai isyarat menolak bala dan kemarau.",
    "doa": [
      {
        "title": "Doa Meminta Hujan Masyhur (Rasulullah SAW)",
        "arabic": "اللَّهُمَّ اسْقِنَا غَيْثًا مُغِيثًا مَرِيئًا مَرِيعًا نَافِعًا غَيْرَ ضَارٍّ عَاجِلًا غَيْرَ آجِلٍ. اللَّهُمَّ أَغِثْنَا، اللَّهُمَّ أَغِثْنَا، اللَّهُمَّ أَغِثْنَا. اللَّهُمَّ اسْقِ عِبَادَكَ وَبَهَائِمَكَ وَانْشُرْ رَحْمَتَكَ وَأَحْيِ بَلَدَكَ الْمَيِّتَ.",
        "rumi": "Allahummas-qina ghaithan mughithan mari'an mari'an nafi'an ghaira darrin 'ajilan ghaira ajil. Allahumma aghithna, Allahumma aghithna, Allahumma aghithna. Allahummas-qi 'ibadaka wa baha'imaka wansyur rahmataka wa ahyi baladakal-mayyit.",
        "translation": "Ya Allah, siramilah kami dengan hujan yang menyelamatkan, menyegarkan, menyuburkan, membawa manfaat dan tidak mendatangkan mudarat, segera dan tidak bertangguh. Ya Allah, tolonglah kami dengan hujan (3x). Ya Allah, berilah minum kepada hamba-hamba-Mu dan haiwan ternakan-Mu, sebarkanlah rahmat-Mu, dan hidupkanlah bumi negeri-Mu yang mati.",
        "dir": "rtl",
        "sourceRef": "sunan-abi-dawud",
        "sourcePage": "Kitab al-Solat, Hadith No. 1169"
      }
    ],
    "interactiveTool": {
      "toolType": "takbir-tracker",
      "rakaat1Takbir": 7,
      "rakaat2Takbir": 5,
      "intermediateTasbih": "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ"
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-isyraq",
    "slug": "isyraq",
    "title": "Solat Sunat Isyraq",
    "titleArabic": "صَلَاةُ الْإِشْرَاقِ",
    "category": "harian",
    "shortPurpose": "Solat sunat awal pagi sejurus matahari terbit sempurna bagi meraih ganjaran pahala haji dan umrah.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Kira-kira 12 hingga 20 minit selepas waktu Syuruk (apabila matahari naik setinggi satu tombak/penggalah melepasi waktu tahrim).",
      "suggestedTimeOfDay": "isyraq"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الْإِشْرَاقِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-isyraqi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Isyraq dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Bab Solat Isyraq"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Menunggu Waktu Selepas Syuruk",
        "description": "Duduk berzikir selepas solat Subuh berjemaah sehingga matahari naik melepasi waktu larangan solat (~15 minit selepas syuruk).",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat Isyraq dua rakaat bersama takbir.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rakaat Pertama & Kedua",
        "description": "Membaca Al-Fatihah, surah lazim, rukuk, iktidal, sujud dan tahiyat akhir.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Salam & Wirid",
        "description": "Memberi salam dan membaca doa memohon keberkatan hari.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Isyraq",
        "description": "Rakaat 1: Surah Ad-Dhuha atau Surah Asy-Syams. Rakaat 2: Surah Al-Insyirah atau Surah Al-Kafirun.",
        "recommendedSurahs": [
          "Ad-Dhuha",
          "Asy-Syams",
          "Al-Insyirah",
          "Al-Kafirun"
        ]
      }
    ],
    "commonLocalPractice": "Jemaah di Malaysia lazimnya kekal berada di masjid selepas Subuh dengan mengikuti kuliah subuh atau tadarus sehingga waktu Isyraq masuk sebelum menunaikan solat ini.",
    "variationsNotes": "Sebahagian ulama Syafi'iyyah menyamakan solat Isyraq dengan solat Dhuha pada waktu awalnya, manakala sebahagian lagi menganggapnya sebagai dua solat sunat yang berasingan.",
    "doa": [
      {
        "title": "Doa Selepas Solat Sunat Isyraq",
        "arabic": "الْحَمْدُ لِلَّهِ الَّذِي جَعَلَ الْيَوْمَ عَافِيَةً وَجَاءَ بِالشَّمْسِ مِنْ مَطْلَعِهَا، اللَّهُمَّ ارْزُقْنِي خَيْرَ هَذَا الْيَوْمِ وَادْفَعْ عَنِّي شَرَّهُ، اللَّهُمَّ نَوِّرْ قَلْبِي بِنُورِ هِدَايَتِكَ كَمَا نَوَّرْتَ الْأَرْضَ بِنُورِ شَمْسِكَ أَبَدًا أَبَدًا بِرَحْمَتِكَ يَا أَرْحَمَ الرَّاحِمِينَ.",
        "rumi": "Alhamdulillahillazi ja'alal-yauma 'afiyatan wa ja'a bisy-syamsi min matla'iha, Allahummar-zuqni khaira hazal-yaumi wadfa' 'anni syarrahu, Allahumma nawwir qalbi binuri hidayatika kama nawwartal-arda binuri syamsika abadan abada, birahmatika ya arhamar-rahimin.",
        "translation": "Segala puji bagi Allah yang menjadikan hari ini penuh kesejahteraan dan menerbitkan matahari dari tempat terbitnya. Ya Allah, kurniakanlah kepadaku kebaikan hari ini dan jauhkanlah daripadaku keburukannya. Ya Allah, terangilah hatiku dengan cahaya hidayah-Mu sebagaimana Engkau menerangi bumi dengan cahaya matahari-Mu buat selama-lamanya, dengan rahmat-Mu wahai Tuhan Yang Maha Pengasih.",
        "dir": "rtl",
        "sourceRef": "al-azkar-nawawi",
        "sourcePage": "Doa Awal Pagi"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-musafir",
    "slug": "musafir",
    "title": "Solat Sunat Musafir",
    "titleArabic": "صَلَاةُ السَّفَرِ",
    "category": "hajat",
    "shortPurpose": "Memohon perlindungan, keselamatan, dan kelancaran daripada Allah SWT ketika hendak memulakan perjalanan atau sejurus tiba.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Sebelum bertolak meninggalkan rumah, atau sebaik tiba di destinasi / kembali ke tempat kediaman (dilakukan di masjid terdekat atau di rumah).",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ السَّفَرِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatas-safari rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat musafir dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Musafir"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Dilakukan sebelum keluar melangkah meninggalkan rumah musafir.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rakaat 1 & 2",
        "description": "Membaca Al-Fatihah, surah lazim, rukuk, iktidal, sujud dua kali dan tahiyat akhir.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Salam & Doa Musafir",
        "description": "Memberi salam dan membaca doa memohon keselamatan musafir.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Musafir",
        "description": "Rakaat 1: Surah Al-Kafirun. Rakaat 2: Surah Al-Ikhlas.",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Umat Islam di Malaysia lazimnya menunaikan solat ini sebelum berangkat menunaikan ibadah Haji, Umrah, atau perjalanan jauh ke luar negeri.",
    "variationsNotes": "Disunatkan juga menunaikan solat sunat dua rakaat sebaik sahaja pulang dari musafir di masjid kariah sebelum masuk ke rumah mengikut sunnah Rasulullah SAW.",
    "doa": [
      {
        "title": "Doa Memulakan Musafir (Sahih Muslim)",
        "arabic": "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ، اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ.",
        "rumi": "Allahumma inna nas'aluka fi safarina haza al-birra wat-taqwa, wa minal-'amali ma tarda, Allahumma hawwin 'alaina safarana haza watwi 'anna bu'dahu, Allahumma antas-sahibu fis-safari wal-khalifatu fil-ahli.",
        "translation": "Ya Allah, sesungguhnya kami memohon kepada-Mu dalam perjalanan kami ini kebajikan dan ketakwaan, serta amalan yang Engkau redhai. Ya Allah, permudahkanlah perjalanan kami ini dan dekatkanlah kejauhannya. Ya Allah, Engkaulah Teman dalam perjalanan dan Penjaga bagi keluarga yang ditinggalkan.",
        "dir": "rtl",
        "sourceRef": "sahih-muslim",
        "sourcePage": "Kitab al-Hajj, Hadith No. 1342"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-mutlak",
    "slug": "mutlak",
    "title": "Solat Sunat Mutlak",
    "titleArabic": "صَلَاةُ النَّفْلِ الْمُطْلَقِ",
    "category": "harian",
    "shortPurpose": "Solat sunat umum bagi mendekatkan diri kepada Allah tanpa terikat waktu, bilangan rakaat, atau sebab tertentu.",
    "hukum": "Sunat",
    "rakaatOptions": [
      2,
      4
    ],
    "timeGuidance": {
      "description": "Bila-bila masa sahaja siang atau malam, kecuali pada 5 waktu yang diharamkan solat sunat tanpa sebab (tahrim).",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "2 Rakaat",
        "arabic": "أُصَلِّي سُنَّةً رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatan rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Mutlak"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat mutlak semata-mata kerana Allah.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Al-Fatihah & Surah Pilihan",
        "description": "Membaca al-Fatihah dan surah yang dihafal.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rukuk, I'tidal, Sujud & Salam",
        "description": "Menyempurnakan setiap rukun perbuatan dengan tumakninah.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Bebas Memilih Surah",
        "description": "Boleh membaca mana-mana surah dari Al-Quran mengikut kelapangan dan kekhusyukan.",
        "recommendedSurahs": [
          "Al-Ikhlas",
          "Al-Falaq",
          "An-Nas"
        ]
      }
    ],
    "commonLocalPractice": "Dilakukan ketika mengisi waktu terluang semasa iktikaf di masjid atau ketika menghadiri majlis ilmu sebelum majlis bermula.",
    "variationsNotes": "5 waktu yang diharamkan solat sunat mutlak: 1. Selepas Subuh hingga matahari terbit. 2. Waktu Syuruk hingga matahari naik setinggi tombak. 3. Waktu rembang (matahari tepat di tengah langit kecuali hari Jumaat). 4. Selepas Asar hingga matahari mula terbenam. 5. Ketika matahari sedang terbenam.",
    "doa": [
      {
        "title": "Doa Memohon Rahmat & Kebaikan",
        "arabic": "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        "rumi": "Rabbana atina fid-dunya hasanah wa fil-akhirati hasanah wa qina 'azaban-nar",
        "translation": "Wahai Tuhan kami, kurniakanlah kepada kami kebaikan di dunia dan kebaikan di akhirat, serta peliharalah kami daripada azab api neraka.",
        "dir": "rtl",
        "sourceRef": "sahih-bukhari",
        "sourcePage": "Kitab al-Da'awat, Hadith No. 6389"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-rawatib",
    "slug": "rawatib",
    "title": "Solat Sunat Rawatib",
    "titleArabic": "صَلَاةُ الرَّوَاتِبِ",
    "category": "harian",
    "shortPurpose": "Solat pengiring solat fardu lima waktu, menyempurnakan sebarang kekurangan pahala solat fardu.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2,
      4,
      10,
      12
    ],
    "timeGuidance": {
      "description": "Mengiringi setiap solat fardu: Sebelum (Qabliyyah) bermula selepas azan hingga solat fardu; Selepas (Ba'diyyah) bermula selesai solat fardu hingga habis waktu solat.",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Qabliyyah Subuh (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الصُّبْحِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatas-subhi rak'ataini qabliyyatan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat sebelum Subuh dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Rawatib Subuh"
      },
      {
        "label": "Qabliyyah Zohor (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الظُّهْرِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnataz-zuhri rak'ataini qabliyyatan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat sebelum Zohor dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Rawatib Zohor"
      },
      {
        "label": "Ba'diyyah Maghrib (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الْمَغْرِبِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-maghribi rak'ataini ba'diyyatan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat selepas Maghrib dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Rawatib Maghrib"
      },
      {
        "label": "Ba'diyyah Isyak (2 Rakaat)",
        "arabic": "أُصَلِّي سُنَّةَ الْعِشَاءِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-'isya'i rak'ataini ba'diyyatan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat selepas Isyak dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Rawatib Isyak"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat Mengikut Waktu Fardu",
        "description": "Menyatakan jenis solat (Qabliyyah atau Ba'diyyah) bersama fardu berkenaan.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Dua Rakaat Ringkas & Khusyuk",
        "description": "Membaca Al-Fatihah, surah lazim, rukuk, iktidal, sujud dan tahiyat akhir.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Salam & Wirid Lazim",
        "description": "Memberi salam dan menyambung zikir atau persiapan solat fardu.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Rawatib Subuh",
        "description": "Rasulullah SAW melazimi bacaan Surah Al-Kafirun pada rakaat pertama dan Surah Al-Ikhlas pada rakaat kedua Qabliyyah Subuh.",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, rawatib Qabliyyah Subuh, Ba'diyyah Maghrib, dan Ba'diyyah Isyak adalah antara yang paling lazim diamalkan di masjid dan di rumah.",
    "variationsNotes": "10/12 Rakaat Muakkad: 2 Subuh (Qabliyyah), 2 atau 4 Zohor (Qabliyyah), 2 Zohor (Ba'diyyah), 2 Maghrib (Ba'diyyah), 2 Isyak (Ba'diyyah). Ghairu Muakkad: 2 tambahan Zohor Qabliyyah, 2 tambahan Zohor Ba'diyyah, 4 Asar Qabliyyah, 2 Maghrib Qabliyyah, 2 Isyak Qabliyyah.",
    "doa": [
      {
        "title": "Fadhilat Rawatib Hadis Ummu Habibah",
        "arabic": "مَنْ صَلَّى فِي يَوْمٍ وَلَيْلَةٍ ثِنْتَيْ عَشْرَةَ رَكْعَةً بُنِيَ لَهُ بَيْتٌ فِي الْجَنَّةِ",
        "rumi": "Man salla fi yaumin wa lailatin thintai 'asyrota rak'atan buniya lahu baitun fil-jannah",
        "translation": "Barang siapa yang mengerjakan solat sunat dua belas rakaat dalam sehari semalam, nescaya dibina untuknya sebuah rumah di dalam syurga.",
        "dir": "rtl",
        "sourceRef": "sahih-muslim",
        "sourcePage": "Kitab Solat al-Musafirin, Hadith No. 728"
      }
    ],
    "interactiveTool": {
      "toolType": "rawatib-grid",
      "muakkadRakaat": 10,
      "ghairuMuakkadRakaat": 12,
      "schedule": [
        {
          "prayer": "Subuh",
          "qabliyyah": "2 Rakaat (Muakkad)",
          "ba'diyyah": "Tiada (Waktu Tahrim)",
          "isMuakkad": true
        },
        {
          "prayer": "Zohor",
          "qabliyyah": "2 Rakaat (Muakkad) + 2 (Ghairu)",
          "ba'diyyah": "2 Rakaat (Muakkad) + 2 (Ghairu)",
          "isMuakkad": true
        },
        {
          "prayer": "Asar",
          "qabliyyah": "4 Rakaat (Ghairu Muakkad)",
          "ba'diyyah": "Tiada (Waktu Tahrim)",
          "isMuakkad": false
        },
        {
          "prayer": "Maghrib",
          "qabliyyah": "2 Rakaat (Ghairu Muakkad)",
          "ba'diyyah": "2 Rakaat (Muakkad)",
          "isMuakkad": true
        },
        {
          "prayer": "Isyak",
          "qabliyyah": "2 Rakaat (Ghairu Muakkad)",
          "ba'diyyah": "2 Rakaat (Muakkad)",
          "isMuakkad": true
        }
      ]
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-tahajjud",
    "slug": "tahajjud",
    "title": "Solat Sunat Tahajjud",
    "titleArabic": "صَلَاةُ التَّهَجُّدِ",
    "category": "malam",
    "shortPurpose": "Solat malam yang paling afdal selepas solat fardu, dikerjakan selepas bangun daripada tidur.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2,
      4,
      8
    ],
    "timeGuidance": {
      "description": "Dilakukan pada waktu malam selepas solat Isyak dengan syarat bangun daripada tidur (walaupun tidur seketika). Waktu paling afdal adalah sepertiga akhir malam (~2.30 pagi hingga sebelum Subuh).",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "2 Rakaat",
        "arabic": "أُصَلِّي سُنَّةَ التَّهَجُّدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tahajjudi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Tahajjud dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Tahajjud"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Bangun Daripada Tidur & Bersugi",
        "description": "Bangun pada waktu malam, disunatkan bersugi/menggosok gigi, berwuduk, dan memandang ke langit membaca 10 ayat terakhir Surah Ali Imran.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat Tahajjud dua rakaat bersama takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Dua Rakaat Khusyuk",
        "description": "Membaca Al-Fatihah, surah panjang mengikut kemampuan, memanjangkan rukuk dan sujud.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Tahiyat Akhir & Salam",
        "description": "Menyempurnakan tasyahhud, selawat dan memberi salam.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Ditutup dengan Solat Witir",
        "description": "Disunatkan menutup ibadah malam dengan solat sunat Witir jika belum dilakukan.",
        "isRukun": false
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Tahajjud",
        "description": "Disunatkan membaca surah yang mententeramkan hati seperti Al-Mulk, Al-Sajdah, Al-Waqi'ah, atau ayat-ayat tadabbur.",
        "recommendedSurahs": [
          "Al-Mulk",
          "Al-Sajdah",
          "Al-Waqi'ah"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat Tahajjud diamalkan secara individu pada setiap malam dan diadakan secara berjemaah dalam program qiamullail masjid terutamanya pada 10 malam terakhir Ramadan.",
    "variationsNotes": "Tiada batasan maksimum bagi rakaat tahajjud; dikerjakan dua rakaat demi dua rakaat.",
    "doa": [
      {
        "title": "Doa Tahajjud Rasulullah SAW (Sahih al-Bukhari)",
        "arabic": "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ لَكَ مُلْكُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ أَنْتَ نُورُ السَّمَاوَاتِ وَالْأَرْضِ، وَلَكَ الْحَمْدُ أَنْتَ الْحَقُّ وَوَعْدُكَ الْحَقُّ وَلِقَاؤُكَ حَقٌّ وَقَوْلُكَ حَقٌّ وَالْجَنَّةُ حَقٌّ وَالنَّارُ حَقٌّ وَالنَّبِيُّونَ حَقٌّ وَمُحَمَّدٌ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَقٌّ وَالسَّاعَةُ حَقٌّ. اللَّهُمَّ لَكَ أَسْلَمْتُ، وَبِكَ آمَنْتُ، وَعَلَيْكَ تَوَكَّلْتُ، وَإِلَيْكَ أَنَبْتُ، وَبِكَ خَاصَمْتُ، وَإِلَيْكَ حَاكَمْتُ، فَاغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ، وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ، أَنْتَ الْمُقَدِّمُ وَأَنْتَ الْمُؤَخِّرُ، لَا إِلَهَ إِلَّا أَنْتَ.",
        "rumi": "Allahumma lakal-hamdu anta qayyimus-samawati wal-ardi wa man fihinna, wa lakal-hamdu laka mulkus-samawati wal-ardi wa man fihinna, wa lakal-hamdu anta nurus-samawati wal-ardi, wa lakal-hamdu antal-haqqu wa wa'dukal-haqqu wa liqa'uka haqqun wa qawluka haqqun wal-jannatu haqqun wan-naru haqqun wan-nabiyyuna haqqun wa Muhammadun sallallahu 'alaihi wa sallama haqqun was-sa'atu haqqun. Allahumma laka aslamtu, wa bika amantu, wa 'alaika tawakkaltu, wa ilaika anabtu, wa bika khasamtu, wa ilaika hakamtu, faghfir li ma qaddamtu wa ma akhkhartu, wa ma asrartu wa ma a'lantu, antal-muqaddimu wa antal-mu'akhkhiru, la ilaha illa anta.",
        "translation": "Ya Allah, bagi-Mu segala puji, Engkaulah Penegak langit dan bumi serta segala isinya. Bagi-Mu segala puji, milik-Mu kerajaan langit dan bumi serta segala isinya. Bagi-Mu segala puji, Engkaulah Cahaya langit dan bumi. Bagi-Mu segala puji, Engkaulah Yang Maha Benar, janji-Mu benar, pertemuan dengan-Mu benar, firman-Mu benar, syurga itu benar, neraka itu benar, para nabi itu benar, Nabi Muhammad SAW itu benar, dan hari kiamat itu benar. Ya Allah, kepada-Mu aku berserah, dengan-Mu aku beriman, kepada-Mu aku bertawakal, kepada-Mu aku kembali, kerana-Mu aku berjuang, dan kepada-Mu aku berhukum. Maka ampunilah dosaku yang telah lalu dan yang akan datang, yang tersembunyi dan yang nyata. Engkaulah Yang Mendahulukan dan Engkaulah Yang Mengakhirkan, tiada Tuhan melainkan Engkau.",
        "dir": "rtl",
        "sourceRef": "sahih-bukhari",
        "sourcePage": "Kitab al-Tahajjud, Hadith No. 1120"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-tahiyatul-masjid",
    "slug": "tahiyatul-masjid",
    "title": "Solat Sunat Tahiyatul Masjid",
    "titleArabic": "صَلَاةُ تَحِيَّةِ الْمَسْجِدِ",
    "category": "harian",
    "shortPurpose": "Menghormati dan memuliakan masjid sebagai rumah Allah SWT setiap kali memasukinya sebelum duduk.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Setiap kali memasuki masjid atau surau yang didirikan solat Jumaat, sebelum seseorang melabuhkan punggung untuk duduk.",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ تَحِيَّةِ الْمَسْجِدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnata tahiyyatil-masjidi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat Tahiyatul Masjid dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Tahiyatul Masjid"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Adab Masuk Masjid",
        "description": "Melangkah dengan kaki kanan dan membaca doa masuk masjid.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat & Takbiratul Ihram",
        "description": "Dilakukan sebelum duduk di dalam masjid.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Menunaikan 2 Rakaat",
        "description": "Menyempurnakan al-Fatihah, rukuk, sujud, tahiyat akhir dan salam.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan",
        "description": "Rakaat 1: Surah Al-Kafirun. Rakaat 2: Surah Al-Ikhlas.",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Jemaah di Malaysia sentiasa mendirikan solat ini setiap kali menghadiri solat Jumaat, termasuk ketika khatib sedang menyampaikan khutbah (dikerjakan secara ringkas/khafifatain mengikut sunnah sahih).",
    "variationsNotes": "Sekiranya terhalang mendirikan solat (contohnya imam telah memulakan solat fardu atau tiada wuduk), disunatkan menggantikannya dengan membaca zikir 4 kali: 'Subhanallah walhamdulillah wa la ilaha illallah wallahu akbar'.",
    "doa": [
      {
        "title": "Doa Masuk Masjid (Sebelum Solat)",
        "arabic": "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
        "rumi": "Allahummaf-tah li abwaba rahmatik",
        "translation": "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.",
        "dir": "rtl",
        "sourceRef": "sahih-muslim",
        "sourcePage": "Kitab Solat al-Musafirin, Hadith No. 713"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-tarawih",
    "slug": "tarawih",
    "title": "Solat Sunat Tarawih",
    "titleArabic": "صَلَاةُ التَّرَاوِيحِ",
    "category": "malam",
    "shortPurpose": "Solat khusus menghidupkan malam-malam Ramadan (Qiam Ramadan) demi meraih keampunan dosa.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      8,
      20
    ],
    "timeGuidance": {
      "description": "Hanya pada malam bulan Ramadan, dilaksanakan selepas solat fardu Isyak dan solat sunat ba'diyyah Isyak sehingga sebelum terbit fajar Subuh.",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ التَّرَاوِيحِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tarawihi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat tarawih dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-tarawih",
        "sourcePage": "Panduan Solat Sunat Tarawih JAKIM, m/s 7"
      },
      {
        "label": "Makmum",
        "arabic": "أُصَلِّي سُنَّةَ التَّرَاوِيحِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tarawihi rak'ataini makmuman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat tarawih dua rakaat sebagai makmum kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-tarawih",
        "sourcePage": "Panduan Solat Sunat Tarawih JAKIM, m/s 7"
      },
      {
        "label": "Imam",
        "arabic": "أُصَلِّي سُنَّةَ التَّرَاوِيحِ رَكْعَتَيْنِ إِمَامًا لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tarawihi rak'ataini imaman lillahi ta'ala",
        "translation": "Sahaja aku solat sunat tarawih dua rakaat sebagai imam kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-tarawih",
        "sourcePage": "Panduan Solat Sunat Tarawih JAKIM, m/s 7"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat sunat tarawih dua rakaat bersama takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Al-Fatihah & Surah",
        "description": "Membaca Al-Fatihah dan surah pilihan mengikut susunan lazim.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rukuk, I'tidal & Dua Sujud",
        "description": "Melakukan rukun perbuatan dengan tumakninah.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Rakaat Kedua & Salam",
        "description": "Menyempurnakan rakaat kedua, membaca tahiyat akhir dan memberi salam.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Mengulangi 2 Rakaat demi 2 Rakaat",
        "description": "Dikerjakan 4 salam (8 rakaat) atau 10 salam (20 rakaat). Diakhiri dengan solat sunat Witir.",
        "isRukun": false
      }
    ],
    "recommendedPractice": [
      {
        "title": "Susunan Surah Lazim Tarawih",
        "description": "Pada rakaat pertama lazimnya dibaca surah-surah lazim bermula daripada At-Takasur hingga Al-Masad, dan rakaat kedua dibaca Surah Al-Ikhlas.",
        "recommendedSurahs": [
          "At-Takasur",
          "Al-Asr",
          "Al-Humazah",
          "Al-Fil",
          "Quraisy",
          "Al-Ma'un",
          "Al-Kautsar",
          "Al-Kafirun",
          "An-Nasr",
          "Al-Masad",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di masjid dan surau Malaysia, sebahagian besar menunaikan 20 rakaat mengikut tradisi para sahabat dan khalifah Umar bin al-Khattab r.a., manakala sebahagian lagi mendirikan 8 rakaat. Diselangi selawat dan bacaan doa antara salam.",
    "variationsNotes": "Solat tarawih mesti dilakukan dengan 1 salam bagi setiap 2 rakaat. Jika digabungkan 4 rakaat 1 salam, solat tarawih tersebut tidak sah mengikut Mazhab Syafi'i.",
    "doa": [
      {
        "title": "Doa Kamilin Selepas Solat Tarawih",
        "arabic": "اللَّهُمَّ اجْعَلْنَا بِالْإِيمَانِ كَامِلِينَ، وَلِلْفَرَائِضِ مُؤَدِّينَ، وَلِلصَّلَاةِ حَافِظِينَ، وَلِلزَّكَاةِ فَاعِلِينَ، وَلِمَا عِنْدَكَ طَالِبِينَ، وَلِعَفْوِكَ رَاجِينَ، وَبِالْهُدَى مُتَمَسِّكِينَ، وَعَنِ اللَّغْوِ مُعْرِضِينَ.",
        "rumi": "Allahummaj'alna bil-imani kamilin, wa lil-fara'idi mu'addin, wa lis-salati hafizin, wa liz-zakati fa'ilin, wa lima 'indaka talibin, wa li'afwika rajin, wa bil-huda mutamassikin, wa 'anil-laghwi mu'ridin.",
        "translation": "Ya Allah, jadikanlah kami orang-orang yang sempurna imannya, menunaikan segala kewajipan fardu, memelihara solat, mengeluarkan zakat, menuntut apa yang ada di sisi-Mu, mengharapkan keampunan-Mu, berpegang teguh dengan petunjuk, dan berpaling daripada perkara yang sia-sia.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-tarawih",
        "sourcePage": "Doa Kamilin, m/s 15"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-tasbih",
    "slug": "tasbih",
    "title": "Solat Sunat Tasbih",
    "titleArabic": "صَلَاةُ التَّسْبِيحِ",
    "category": "raya_fenomena",
    "shortPurpose": "Solat khusus mengandungi 300 tasbih memohon keampunan bagi dosa terdahulu, masa kini, sengaja mahupun tidak.",
    "hukum": "Sunat",
    "rakaatOptions": [
      4
    ],
    "timeGuidance": {
      "description": "Boleh ditunaikan pada siang hari (4 rakaat 1 salam) atau pada malam hari (4 rakaat 2 salam). Disarankan sekurang-kurangnya sekali seumur hidup atau seminggu sekali.",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Siang Hari (4 Rakaat 1 Salam)",
        "arabic": "أُصَلِّي سُنَّةَ التَّسْبِيحِ أَرْبَعَ رَكَعَاتٍ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tasbihi arba'a raka'atin lillahi ta'ala",
        "translation": "Sahaja aku solat sunat tasbih empat rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Tasbih"
      },
      {
        "label": "Malam Hari (2 Rakaat 1 Salam)",
        "arabic": "أُصَلِّي سُنَّةَ التَّسْبِيحِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-tasbihi rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat tasbih dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Tasbih"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram",
        "description": "Niat solat tasbih berserta takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Qiyam & Bacaan Surah (15x Tasbih)",
        "description": "Membaca Al-Fatihah dan surah pilihan, kemudian membaca tasbih khusus sebanyak 15 kali sebelum rukuk.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Rukuk (10x Tasbih)",
        "description": "Membaca tasbih rukuk lazim, disusuli tasbih solat tasbih 10 kali.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "I'tidal (10x Tasbih)",
        "description": "Bangkit iktidal, membaca tahmid, disusuli tasbih solat tasbih 10 kali.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "Sujud Pertama (10x Tasbih)",
        "description": "Sujud membaca tasbih sujud biasa, disusuli tasbih solat tasbih 10 kali.",
        "isRukun": true
      },
      {
        "stepNumber": 6,
        "title": "Duduk Antara Dua Sujud (10x Tasbih)",
        "description": "Duduk membaca doa rabighfirli, disusuli tasbih solat tasbih 10 kali.",
        "isRukun": true
      },
      {
        "stepNumber": 7,
        "title": "Sujud Kedua (10x Tasbih)",
        "description": "Sujud kedua membaca tasbih sujud, disusuli tasbih solat tasbih 10 kali.",
        "isRukun": true
      },
      {
        "stepNumber": 8,
        "title": "Duduk Istirahah / Tahiyat (10x Tasbih)",
        "description": "Sebelum berdiri ke rakaat berikutnya (atau semasa duduk tasyahhud sebelum tasyahhud), membaca tasbih 10 kali. Jumlah rakaat = 75x.",
        "isRukun": true
      },
      {
        "stepNumber": 9,
        "title": "Menyempurnakan 4 Rakaat (Jumlah 300x)",
        "description": "Ulangi aturan 75 tasbih untuk setiap rakaat sehingga genap 300 tasbih.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan 4 Rakaat",
        "description": "Rakaat 1: Surah At-Takasur. Rakaat 2: Surah Al-Asr. Rakaat 3: Surah Al-Kafirun. Rakaat 4: Surah Al-Ikhlas.",
        "recommendedSurahs": [
          "At-Takasur",
          "Al-Asr",
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat tasbih sering dilakukan secara berjemaah pada malam-malam berkat seperti Nisfu Sya'ban, 10 malam terakhir Ramadan, atau malam Jumaat di surau dan masjid.",
    "variationsNotes": "Jika terlupa membaca tasbih di satu posisi (contohnya ketika rukuk), boleh digantikan bilangannya pada posisi berikutnya mengikut pandangan ulama Mazhab Syafi'i.",
    "doa": [
      {
        "title": "Teks Bacaan Tasbih Solat Tasbih (75x per Rakaat)",
        "arabic": "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ",
        "rumi": "Subhanallah walhamdulillah wa la ilaha illallah wallahu akbar, wa la haula wa la quwwata illa billahil-'aliyyil-'azim",
        "translation": "Maha Suci Allah, segala puji bagi Allah, tiada Tuhan yang berhak disembah melainkan Allah, dan Allah Maha Besar. Tiada daya dan kekuatan melainkan dengan pertolongan Allah Yang Maha Tinggi lagi Maha Agung.",
        "dir": "rtl",
        "sourceRef": "sunan-tirmidhi",
        "sourcePage": "Kitab al-Solat, Hadith No. 481"
      },
      {
        "title": "Doa Selepas Solat Sunat Tasbih",
        "arabic": "اللَّهُمَّ إِنِّي أَسْأَلُكَ تَوْفِيقَ أَهْلِ الْهُدَى، وَأَعْمَالَ أَهْلِ الْيَقِينِ، وَمُنَاصَحَةَ أَهْلِ التَّوْبَةِ، وَعَزْمَ أَهْلِ الصَّبْرِ، وَوَجَلَ أَهْلِ الْخَشْيَةِ، وَطَلَبَ أَهْلِ الرَّغْبَةِ، وَتَعَبُّدَ أَهْلِ الْوَرَعِ، وَعِرْفَانَ أَهْلِ الْعِلْمِ حَتَّى أَخَافَكَ.",
        "rumi": "Allahumma inni as'aluka taufiqa ahlil-huda, wa a'mala ahlil-yaqin, wa munasahata ahlit-taubah, wa 'azma ahlis-sabr, wa wajala ahlil-khasyyah, wa talaba ahlir-raghbah, wa ta'abbuda ahlil-wara', wa 'irfana ahlil-'ilmi hatta akhafak.",
        "translation": "Ya Allah, sesungguhnya aku memohon kepada-Mu taufik orang-orang yang beroleh petunjuk, amalan orang-orang yang yakin, ketulusan orang-orang yang bertaubat, keazaman orang-orang yang sabar, rasa gerun orang-orang yang takutkan-Mu, pencarian orang-orang yang mencintai rahmat-Mu, ibadah orang-orang yang warak, dan makrifat orang-orang yang berilmu sehingga aku benar-benar takut kepada-Mu.",
        "dir": "rtl",
        "sourceRef": "sunan-tirmidhi",
        "sourcePage": "Bab Doa Solat Tasbih"
      }
    ],
    "interactiveTool": {
      "toolType": "tasbih-counter",
      "totalTasbih": 300,
      "rakaatCount": 4,
      "tasbihPerRakaat": 75,
      "positions": [
        {
          "positionIndex": 1,
          "name": "Qiyam selepas bacaan surah",
          "count": 15
        },
        {
          "positionIndex": 2,
          "name": "Dalam rukuk selepas tasbih rukuk",
          "count": 10
        },
        {
          "positionIndex": 3,
          "name": "Dalam iktidal selepas tahmid",
          "count": 10
        },
        {
          "positionIndex": 4,
          "name": "Dalam sujud pertama selepas tasbih sujud",
          "count": 10
        },
        {
          "positionIndex": 5,
          "name": "Duduk antara dua sujud selepas doa",
          "count": 10
        },
        {
          "positionIndex": 6,
          "name": "Dalam sujud kedua selepas tasbih sujud",
          "count": 10
        },
        {
          "positionIndex": 7,
          "name": "Duduk istirahah / sebelum bangkit / tahiyat",
          "count": 10
        }
      ]
    },
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-taubat",
    "slug": "taubat",
    "title": "Solat Sunat Taubat",
    "titleArabic": "صَلَاةُ التَّوْبَةِ",
    "category": "malam",
    "shortPurpose": "Solat khusus menyesali keterlanjuran dosa serta memohon keampunan yang tulus daripada Allah SWT.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Bila-bila masa sahaja sebaik tersedar daripada dosa dan kesalahan. Waktu paling afdal adalah pada waktu sunyi malam (sepertiga akhir malam).",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ التَّوْبَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatat-taubati rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat taubat dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Solat Sunat Taubat"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Menghadirkan Penyesalan yang Sungguh",
        "description": "Syarat taubat nasuha: menyesali dosa, berhenti serta-merta, dan berazam tidak mengulanginya.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat & Takbiratul Ihram",
        "description": "Takbiratul ihram berserta niat solat sunat taubat.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Dua Rakaat Sempurna",
        "description": "Membaca al-Fatihah, surah lazim, rukuk, iktidal, sujud dan tahiyat akhir.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Sujud Akhir & Istighfar",
        "description": "Sunat memanjangkan sujud akhir sambil memohon ampun dengan penuh khusyuk dan linangan air mata.",
        "isRukun": false
      },
      {
        "stepNumber": 5,
        "title": "Salam & Membaca Sayyidul Istighfar",
        "description": "Memberi salam dan melazimkan istighfar serta doa taubat.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Taubat",
        "description": "Rakaat 1: Surah Al-Kafirun. Rakaat 2: Surah Al-Ikhlas (atau Surah Al-Falaq / An-Nas).",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat taubat sering diiringi dengan bacaan istighfar 100 kali dan doa Nabi Yunus a.s. dalam sujud akhir atau selepas salam.",
    "variationsNotes": "Jika dosa melibatkan hak sesama manusia, syarat sah taubat mestilah mengembalikan hak tersebut atau memohon kemaafan dan kehalalan daripadanya.",
    "doa": [
      {
        "title": "Sayyidul Istighfar (Penghulu Istighfar)",
        "arabic": "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ.",
        "rumi": "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'uzu bika min syarri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u bizanbi faghfir li fa-innahu la yaghfiruz-zunuba illa anta.",
        "translation": "Ya Allah, Engkaulah Tuhanku, tiada Tuhan yang berhak disembah melainkan Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku berada dalam perjanjian dan janji-Mu sekadar kemampuanku. Aku berlindung dengan-Mu daripada kejahatan apa yang telah aku lakukan. Aku mengakui nikmat-Mu ke atasku dan aku mengakui dosaku, maka ampunilah aku, sesungguhnya tiada yang dapat mengampunkan segala dosa melainkan Engkau.",
        "dir": "rtl",
        "sourceRef": "sahih-bukhari",
        "sourcePage": "Kitab al-Da'awat, Hadith No. 6306"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-witir",
    "slug": "witir",
    "title": "Solat Sunat Witir",
    "titleArabic": "صَلَاةُ سُنَّةِ الْوِتْرِ",
    "category": "malam",
    "shortPurpose": "Solat ganjil sebagai penutup segala solat malam dan ibadah qiamullail.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      1,
      3,
      5,
      7,
      9,
      11
    ],
    "timeGuidance": {
      "description": "Bermula selepas menunaikan solat fardu Isyak (dan ba'diyyah) sehingga terbit fajar sadiq (masuk waktu Subuh). Paling afdal di penghujung malam bagi yang bangun bertahajjud.",
      "suggestedTimeOfDay": "malam"
    },
    "niat": [
      {
        "label": "2 Rakaat Pertama (Daripada Witir)",
        "arabic": "أُصَلِّي سُنَّةً مِنَ الْوِتْرِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatan minal-witri rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat dua rakaat daripada solat witir kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Bab Solat Witir"
      },
      {
        "label": "1 Rakaat Terakhir",
        "arabic": "أُصَلِّي سُنَّةَ الْوِتْرِ رَكْعَةً لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-witri rak'atan lillahi ta'ala",
        "translation": "Sahaja aku solat sunat witir satu rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Bab Solat Witir"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Niat & Takbiratul Ihram (Set 2 Rakaat)",
        "description": "Berniat dua rakaat daripada witir bersama takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 2,
        "title": "Rakaat Pertama & Kedua",
        "description": "Membaca Al-Fatihah dan surah, rukuk, iktidal, sujud dua kali, dan duduk tahiyat akhir berserta salam.",
        "isRukun": true
      },
      {
        "stepNumber": 3,
        "title": "Bangkit untuk 1 Rakaat Penutup",
        "description": "Berdiri semula, berniat satu rakaat witir dengan takbiratul ihram.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Bacaan Surah & Doa Qunut (Separuh Akhir Ramadan)",
        "description": "Membaca surah lazim. Mulai malam ke-16 Ramadan, sunat membaca doa qunut pada iktidal rakaat terakhir.",
        "isRukun": false
      },
      {
        "stepNumber": 5,
        "title": "Rukuk, Sujud, Tahiyat Akhir & Salam",
        "description": "Menyempurnakan rukun fi'li dan qauli sehingga salam penutup.",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan Witir 3 Rakaat",
        "description": "Rakaat 1: Surah Al-A'la. Rakaat 2: Surah Al-Kafirun. Rakaat 3: Surah Al-Ikhlas, Al-Falaq, dan An-Nas.",
        "recommendedSurahs": [
          "Al-A'la",
          "Al-Kafirun",
          "Al-Ikhlas",
          "Al-Falaq",
          "An-Nas"
        ]
      }
    ],
    "commonLocalPractice": "Di Malaysia, solat witir lazimnya ditunaikan 3 rakaat (2 rakaat 1 salam + 1 rakaat 1 salam) secara berjemaah selepas solat Tarawih sepanjang Ramadan, disusuli wirid 'Subhanal Malikil Quddus' 3 kali.",
    "variationsNotes": "Boleh dikerjakan secara bersambung (wasal) 3 rakaat dengan 1 salam tanpa tahiyat awal mengikut Mazhab Syafi'i, namun cara fasal (2 rakaat salam + 1 rakaat salam) adalah lebih afdal.",
    "doa": [
      {
        "title": "Zikir Selepas Salam Witir (3x)",
        "arabic": "سُبْحَانَ الْمَلِكِ الْقُدُّوسِ",
        "rumi": "Subhanal-malikil-quddus",
        "translation": "Maha Suci Allah Tuhan Yang Memiliki Kerajaan lagi Maha Suci.",
        "dir": "rtl",
        "sourceRef": "sunan-abi-dawud",
        "sourcePage": "Hadith No. 1430"
      },
      {
        "title": "Doa Solat Witir Masyhur",
        "arabic": "اللَّهُمَّ إِنَّا نَسْأَلُكَ إِيمَانًا دَائِمًا، وَنَسْأَلُكَ قَلْبًا خَاشِعًا، وَنَسْأَلُكَ عِلْمًا نَافِعًا، وَنَسْأَلُكَ يَقِينًا صَادِقًا، وَنَسْأَلُكَ عَمَلًا صَالِحًا، وَنَسْأَلُكَ دِينًا قَيِّمًا، وَنَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ، وَنَسْأَلُكَ تَمَامَ الْعَافِيَةِ، وَنَسْأَلُكَ الشُّكْرَ عَلَى الْعَافِيَةِ، وَنَسْأَلُكَ الْغِنَى عَنِ النَّاسِ.",
        "rumi": "Allahumma inna nas'aluka imanan da'iman, wa nas'aluka qalban khasyi'an, wa nas'aluka 'ilman nafi'an, wa nas'aluka yaqinan sadiqan, wa nas'aluka 'amalan salihan, wa nas'aluka dinan qayyiman, wa nas'aluka al-'afwa wal-'afiyah, wa nas'aluka tamamal-'afiyah, wa nas'aluka asy-syukra 'alal-'afiyah, wa nas'aluka al-ghina 'anin-nas.",
        "translation": "Ya Allah, sesungguhnya kami memohon kepada-Mu iman yang berkekalan, hati yang khusyuk, ilmu yang bermanfaat, keyakinan yang benar, amal yang soleh, agama yang lurus, keampunan dan kesejahteraan, kesempurnaan afiat, rasa syukur atas afiat, dan kecukupan daripada bergantung kepada manusia.",
        "dir": "rtl",
        "sourceRef": "al-azkar-nawawi",
        "sourcePage": "Bab Doa Solat Witir"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  },
  {
    "id": "solat-wuduk",
    "slug": "wuduk",
    "title": "Solat Sunat Wuduk",
    "titleArabic": "صَلَاةُ سُنَّةِ الْوُضُوءِ",
    "category": "harian",
    "shortPurpose": "Menzahirkan kesyukuran atas nikmat bersuci dan menyucikan batin sejurus menyempurnakan wuduk.",
    "hukum": "Sunat Muakkad",
    "rakaatOptions": [
      2
    ],
    "timeGuidance": {
      "description": "Dikerjakan sejurus selepas selesai mengambil wuduk dengan sempurna, sebelum anggota wuduk kering atau sebelum batal wuduk.",
      "suggestedTimeOfDay": "sepanjang-masa"
    },
    "niat": [
      {
        "label": "Sendirian",
        "arabic": "أُصَلِّي سُنَّةَ الْوُضُوءِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
        "rumi": "Usolli sunnatal-wudu'i rak'ataini lillahi ta'ala",
        "translation": "Sahaja aku solat sunat wuduk dua rakaat kerana Allah Taala.",
        "dir": "rtl",
        "sourceRef": "jakim-panduan-solat-sunat",
        "sourcePage": "Panduan Solat Sunat Wuduk, m/s 12"
      }
    ],
    "essentialSteps": [
      {
        "stepNumber": 1,
        "title": "Bersuci & Berwuduk Sempurna",
        "description": "Menyempurnakan wuduk mengikut rukun dan sunat, disusuli bacaan doa selepas wuduk.",
        "isRukun": false
      },
      {
        "stepNumber": 2,
        "title": "Niat & Takbiratul Ihram",
        "description": "Melafazkan takbiratul ihram sambil menghadirkan niat solat sunat wuduk di dalam hati.",
        "isRukun": true,
        "arabic": "اللَّهُ أَكْبَرُ",
        "rumi": "Allahu Akbar",
        "translation": "Allah Maha Besar.",
        "dir": "rtl",
        "sourceRef": "al-fiqh-al-manhaji"
      },
      {
        "stepNumber": 3,
        "title": "Membaca Surah Al-Fatihah",
        "description": "Rukun qauli wajib pada setiap rakaat.",
        "isRukun": true
      },
      {
        "stepNumber": 4,
        "title": "Rukuk serta Tumakninah",
        "description": "Membongkokkan badan sehingga kedua tapak tangan memegang lutut dan bertenang seketika.",
        "isRukun": true
      },
      {
        "stepNumber": 5,
        "title": "I'tidal serta Tumakninah",
        "description": "Bangkit berdiri tegak dari rukuk dan bertenang seketika.",
        "isRukun": true
      },
      {
        "stepNumber": 6,
        "title": "Dua Sujud serta Tumakninah",
        "description": "Sujud meletakkan dahi, kedua tapak tangan, kedua lutut, dan hujung jari kaki ke lantai.",
        "isRukun": true
      },
      {
        "stepNumber": 7,
        "title": "Duduk Antara Dua Sujud",
        "description": "Duduk dengan tenang sambil membaca doa memohon keampunan dan rahmat.",
        "isRukun": true
      },
      {
        "stepNumber": 8,
        "title": "Rakaat Kedua",
        "description": "Bangkit ke rakaat kedua, membaca al-Fatihah, surah pilihan, rukuk, iktidal, dan dua sujud.",
        "isRukun": true
      },
      {
        "stepNumber": 9,
        "title": "Tahiyat Akhir & Selawat",
        "description": "Duduk membaca tasyahhud akhir dan selawat ke atas Nabi Muhammad SAW.",
        "isRukun": true
      },
      {
        "stepNumber": 10,
        "title": "Memberi Salam",
        "description": "Salam pertama memalingkan wajah ke kanan (rukun) dan kedua ke kiri (sunat).",
        "isRukun": true
      }
    ],
    "recommendedPractice": [
      {
        "title": "Surah Pilihan",
        "description": "Disunatkan membaca Surah al-Kafirun pada rakaat pertama dan Surah al-Ikhlas pada rakaat kedua selepas al-Fatihah.",
        "recommendedSurahs": [
          "Al-Kafirun",
          "Al-Ikhlas"
        ]
      }
    ],
    "commonLocalPractice": "Di surau dan masjid di Malaysia, para jemaah lazimnya mendirikan solat sunat wuduk sebaik selesai berwuduk di kolah atau tempat wuduk sebelum duduk beriktikaf.",
    "variationsNotes": "Menurut Mazhab Syafi'i (Al-Kafi #1560), pahala dua rakaat wuduk turut terhasil sekiranya seseorang terus mendirikan solat fardu atau solat sunat lain seperti Tahiyatul Masjid sejurus berwuduk.",
    "doa": [
      {
        "title": "Doa Selepas Wuduk & Solat Wuduk",
        "arabic": "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ، وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ، وَاجْعَلْنِي مِنْ عِبَادِكَ الصَّالِحِينَ.",
        "rumi": "Asyhadu alla ilaha illallahu wahdahu la syarikalah, wa asyhadu anna Muhammadan 'abduhu wa rasuluh. Allahummaj'alni minat-tawwabin, waj'alni minal-mutatahhirin, waj'alni min 'ibadikas-salihin.",
        "translation": "Aku bersaksi bahawa tiada Tuhan yang berhak disembah melainkan Allah Yang Maha Esa, tiada sekutu bagi-Nya, dan aku bersaksi bahawa Nabi Muhammad hamba dan utusan-Nya. Ya Allah, jadikanlah aku daripada golongan orang yang bertaubat, orang yang sentiasa bersuci, dan jadikanlah aku daripada hamba-hamba-Mu yang soleh.",
        "dir": "rtl",
        "sourceRef": "sahih-muslim",
        "sourcePage": "Kitab al-Taharah, Hadith No. 234"
      }
    ],
    "contentVersion": "1.0.0",
    "lastReviewedAt": "2026-09-15",
    "reviewedBy": "Sidang Editorial Fiqh Syafi'i",
    "reviewStatus": "approved"
  }
] as const;

/**
 * Phase 1 structural sample guide preserved for tests and layout verification.
 */
export const sampleGuide: SolatGuide = {
  id: "contoh-struktur",
  slug: "contoh-struktur",
  title: "Contoh struktur panduan",
  titleArabic: "نَصٌّ تَجْرِيبِيٌّ لِلْعَرْضِ فَقَطْ",
  category: "harian",
  shortPurpose: "Sampel teknikal untuk menguji pembacaan dan luar talian; bukan panduan ibadah.",
  hukum: "Sunat",
  rakaatOptions: [2],
  timeGuidance: {
    description: "Sampel teknikal Fasa 1.",
    suggestedTimeOfDay: "sepanjang-masa",
  },
  niat: [
    {
      label: "Sampel Teknikal",
      arabic: "نَصٌّ تَجْرِيبِيٌّ لِلْعَرْضِ فَقَطْ",
      rumi: "Nassun tajribiyyun lil-'ardhi faqat",
      translation: "Teks percubaan untuk paparan teknikal sahaja, bukan panduan ibadah.",
      dir: "rtl",
      sourceRef: "jakim-panduan-solat-sunat",
      sourcePage: "Sampel Ujian Fasa 1",
    },
  ],
  essentialSteps: [
    {
      stepNumber: 1,
      title: "Langkah Sampel Teknikal",
      description: "Halaman ini sengaja tidak mengandungi niat atau hukum kerana belum disemak oleh pihak berautoriti.",
      isRukun: false,
    },
  ],
  recommendedPractice: [],
  commonLocalPractice: "Bukan panduan ibadah sebenar.",
  variationsNotes: "Disediakan untuk ujian asas fasa 1.",
  doa: [],
  contentVersion: "0.1.0",
  lastReviewedAt: null,
  reviewedBy: null,
  reviewStatus: "needs-review",
};

/**
 * All guides including the technical sample for complete static routing.
 */
export const allGuides: readonly SolatGuide[] = [sampleGuide, ...guides] as const;

export function findGuide(slug: string): SolatGuide | undefined {
  if (slug === "contoh-struktur") return sampleGuide;
  return guides.find((guide) => guide.slug === slug);
}

export function findSource(id: string): SourceItem | undefined {
  return sources.find((source) => source.id === id);
}

export function getGuidesByCategory(category: PrayerCategory): SolatGuide[] {
  return guides.filter((guide) => guide.category === category);
}

export function searchGuides(query: string): SolatGuide[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [...guides];
  return guides.filter((guide) => {
    return (
      guide.title.toLowerCase().includes(normalized) ||
      guide.slug.toLowerCase().includes(normalized) ||
      guide.shortPurpose.toLowerCase().includes(normalized) ||
      guide.category.toLowerCase().includes(normalized)
    );
  });
}
